import React from 'react';
import { Globe, Sparkles, Wand2, Brain, type LucideIcon } from 'lucide-react';
import { cn } from '@/lib/utils';

export type MessageSource = 'knowledge' | 'web_search' | 'store_editor' | 'design_generator';

interface SourceConfig {
  label: string;
  icon: LucideIcon;
  className: string;
  tooltip: string;
}

const SOURCE_MAP: Record<MessageSource, SourceConfig> = {
  knowledge: {
    label: 'AI Knowledge',
    icon: Brain,
    className: 'bg-primary/10 text-primary border-primary/20',
    tooltip: "Answer generated from the AI's built-in knowledge",
  },
  web_search: {
    label: 'Web Search',
    icon: Globe,
    className: 'bg-blue-500/10 text-blue-600 border-blue-500/20 dark:text-blue-400',
    tooltip: 'Answer based on real-time web search results',
  },
  store_editor: {
    label: 'Store Editor',
    icon: Wand2,
    className: 'bg-emerald-500/10 text-emerald-600 border-emerald-500/20 dark:text-emerald-400',
    tooltip: 'Answer generated by modifying your store',
  },
  design_generator: {
    label: 'Design Generator',
    icon: Sparkles,
    className: 'bg-fuchsia-500/10 text-fuchsia-600 border-fuchsia-500/20 dark:text-fuchsia-400',
    tooltip: 'Answer generated by the design variants engine',
  },
};

export function MessageSourceBadge({ source }: { source: MessageSource }) {
  const cfg = SOURCE_MAP[source];
  if (!cfg) return null;
  const Icon = cfg.icon;
  return (
    <span
      title={cfg.tooltip}
      className={cn(
        'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium',
        cfg.className
      )}
    >
      <Icon className="h-3 w-3" />
      {cfg.label}
    </span>
  );
}
